name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Running tests
        run: |
          cd src
          python -m pytest addition.py
